## Problem 1 - Basic statistics of the data (2 points)

In this problem your task is to open and explore a NOAA weather data file using pandas. The data file name is `ph_temp_data.csv` and it is located in the `data` folder in this repository. 

### Tips for completing this problem

- Use **exactly** the same variable names as in the instructions.
- **Please do not**:

    - **Change the file names**. Do all of your editing in the provided `Exercise-5-problem-1.ipynb` file (this file).
    - **Change the existing cell types**. You can add cells, but changing the cell types for existing cells (from code to markdown, for example) will also cause the automated grader to fail. 

### Scores for this problem

**Your score on this problem will be based on following criteria:**

- Importing the pandas module
- Reading the data using pandas into a variable called `data`
- Calculating a number of values from the data file used in this problem
- Including comments that explain what most lines in the code do
- Answering a couple questions at the end of the problem
- Uploading your notebook to your GitHub repository for this week's exercise

### Part 1 (0.5 points)

Your first task is to import pandas and read in the data file.

- Import the pandas module
- Read the data into a variable called `data` using pandas 

**Hint**: When reading the data, you need to consider a couple of things:

- The input file is located in the `data` folder, and you need to include this in the filepath when reading the file to pandas
- No-data values are specified with varying number of `*` characters in the input file. You can tell this to pandas by specifying the following parameter in the pandas `read_csv()` function: `na_values=['*', '**', '***', '****', '*****', '******']`

In [3]:
data = None

# imports the pandas module and reads the data into the data variable
import pandas as pd
data = pd.read_csv('ph_tempdata.csv', sep=',', na_values=['*', '**', '***', '****', '*****', '******'])

Check that the first rows of the DataFrame look ok:

In [4]:
data.head()

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,TEMP,MAX,MIN
0,RPM00098646,"MACTAN CEBU INTERNATIONAL, RP",10.308,123.979,9.4,2017-01-01,79.70,86.00,NaN
1,RPM00098646,"MACTAN CEBU INTERNATIONAL, RP",10.308,123.979,9.4,2017-01-02,79.88,85.64,NaN
2,RPM00098646,"MACTAN CEBU INTERNATIONAL, RP",10.308,123.979,9.4,2017-01-03,82.40,88.52,76.64
3,RPM00098646,"MACTAN CEBU INTERNATIONAL, RP",10.308,123.979,9.4,2017-01-04,82.04,89.24,NaN
4,RPM00098646,"MACTAN CEBU INTERNATIONAL, RP",10.308,123.979,9.4,2017-01-05,81.32,88.52,77.00

### Part 2 (0.5 points)

In the cell below, fill in the variables values to print answers to these questions:

- How many rows is there in the data (variable `rows`)?
- What are the column names (variable `column_names`)?
- What are the datatypes of the columns (variable `column_datatypes`)?

In [15]:

row_count = len (data) # returns number of rows
column_names = data.columns # returns the column names
column_datatypes = data.dtypes # returns the datatypes of the columns

In [16]:
# Print the number of rows in the dataframe:
print(f"There are {row_count} rows")

There are 2921 rows

In [17]:
# Print the column names:
print(f"The columns are: \n{column_names}")

The columns are:
Index(['STATION', 'NAME', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'DATE', 'TEMP',
       'MAX', 'MIN'],
      dtype='object')

In [18]:
# Print the column datatypes:
print(f"The column types are: \n{column_datatypes}")

The column types are:
STATION       object
NAME          object
LATITUDE     float64
LONGITUDE    float64
ELEVATION    float64
DATE          object
TEMP         float64
MAX          float64
MIN          float64
dtype: object

### Part 3 (1 point)

In the cell below, fill in the variables values to print answers to these questions:

- What is the mean Fahrenheit temperature in the data (`temp_mean` variable calculated from the `TEMP` column)?
- What is the standard deviation of the maximum temperature (`temp_max_std` variable calculated from the `MAX` column)?
- How many unique stations exists in the data (`station_count` variable calculated from the `STATION` column)?

In [34]:
# Calculate mean temperature
temp_mean = data["TEMP"].mean()

# Calculate standard deviaton of the maximum temperature:
temp_max_std = data["MAX"].std()

#Calculate number of unique stations:
station_count = len(data["STATION"].unique())

# YOUR CODE HERE
data

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,TEMP,MAX,MIN
0,RPM00098646,"MACTAN CEBU INTERNATIONAL, RP",10.308,123.979,9.4,2017-01-01,79.70,86.00,NaN
1,RPM00098646,"MACTAN CEBU INTERNATIONAL, RP",10.308,123.979,9.4,2017-01-02,79.88,85.64,NaN
2,RPM00098646,"MACTAN CEBU INTERNATIONAL, RP",10.308,123.979,9.4,2017-01-03,82.40,88.52,76.64
3,RPM00098646,"MACTAN CEBU INTERNATIONAL, RP",10.308,123.979,9.4,2017-01-04,82.04,89.24,NaN
4,RPM00098646,"MACTAN CEBU INTERNATIONAL, RP",10.308,123.979,9.4,2017-01-05,81.32,88.52,77.00
...,...,...,...,...,...,...,...,...,...
2916,RP000098755,"HINATUAN, RP",8.367,126.333,3.0,2020-12-27,82.58,90.32,74.48
2917,RP000098755,"HINATUAN, RP",8.367,126.333,3.0,2020-12-28,80.78,85.64,NaN
2918,RP000098755,"HINATUAN, RP",8.367,126.333,3.0,2020-12-29,81.68,89.24,76.28
2919,RP000098755,"HINATUAN, RP",8.367,126.333,3.0,2020-12-30,80.42,86.72,76.82
2920,RP000098755,"HINATUAN, RP",8.367,126.333,3.0,2020-12-31,80.24,86.36,NaN

In [35]:
# Check mean temperature value
print(f"The mean temperature in Fahrenheit is {round(temp_mean,1)}")

The mean temperature in Fahrenheit is 81.9

In [36]:
# Check standard deviation value
print(f"The standard deviation of maximum temperature is {round(temp_max_std, 1)}")

The standard deviation of maximum temperature is 3.3

In [37]:
# Check number of stations value
print(f"The number of unique stations is {station_count}")

The number of unique stations is 2

### Problem 1 summary

- Did you have any problems with Problem 1?

Also, make sure to:

- Check that your code includes informative comments explaining what your code does
- Commit and push your changes to your GitHub repository for Exercise 5

Please write your answers and comments below (**activate the cell by double clicking**).

no

### On to Problem 2

Now you can continue to [Problem 2: Data manipulation and selection](Exercise-5-problem-2.ipynb)